---

- name: 'Prepare the run'
  hosts: localhost
  tasks:
   - block:
     - include_role:
         name: dci/prepare_job
     - include_role:
         name: dci/run_user_hooks
     - include_role:
         name: queens/tripleo-inventory
     - name: Ensure the undercloud is ready
       command: test -f /home/stack/stackrc
       delegate_to: "undercloud"
  
     - name: Ensure the overcloud is ready
       command: test -f /home/stack/overcloudrc
       delegate_to: "undercloud"
     rescue:
       - include_role:
           name: dci/close_job
         vars:
           final_status: failure

- name: 'Run the tests'
  hosts: undercloud
  tasks:
    - include_role:
        name: dci/test_campaign

- name: 'Successful installation'
  hosts: localhost
  roles:
    - dci/close_job 
