#!/bin/bash
set -eux
TMPDIR='/tmp/dci-tmp-dir'
BASEDIR=$(pwd)


get_repo() {
    repo=${1}
    roles=${2}
    cd ${TMPDIR}
    git clone https://code.engineering.redhat.com/gerrit/${repo}.git ${repo}
    cd ${repo}
    for topic in OSP8 OSP9 OSP10 OSP11 OSP12; do
        branch=$(echo ${topic}|sed 's,OSP,origin/stable/rhos-,')
        target=${BASEDIR}/roles/${topic}
        mkdir -p ${target}
        git checkout -b ${topic} ${branch}


        # until https://review.openstack.org/#/c/521650 is merged upstream and backported
        [ ${repo} = 'tripleo-quickstart-extras' ] &&  [ ${topic} = "OSP11" ] && git fetch https://git.openstack.org/openstack/tripleo-quickstart-extras refs/changes/50/521650/1 && git cherry-pick FETCH_HEAD
        [ ${repo} = 'tripleo-quickstart-extras' ] &&  [ ${topic} = "OSP10" ] && git fetch https://git.openstack.org/openstack/tripleo-quickstart-extras refs/changes/50/521650/1 && git cherry-pick FETCH_HEAD

        # until https://review.openstack.org/#/c/507889/ is merged upstream and backported on all the branches
        [ ${repo} = 'tripleo-quickstart-extras' ] &&  find -name '*.yml' -exec sed -i "s/lookup('env', 'PWD')/local_working_dir/" "{}" \;

        # until https://review.openstack.org/#/c/518575/ is merged upstream and backported on all the internal branches
        [ ${repo} = 'tripleo-quickstart-extras' ] && git ls-files '*pre-tempest.yml' | xargs sed -i 's/processor_count/processor_vcpus/'

        for i in ${roles}; do
           cp -av roles/${i} ${target}/${i}
        done
	git reset --hard
	git clean -ffdx
    done
}

rm -Rf ${TMPDIR} ${BASEDIR}/roles
mkdir -p ${TMPDIR}
get_repo tripleo-quickstart "common tripleo-inventory"
get_repo tripleo-quickstart-extras "collect-logs extras-common validate-tempest"
