#!/bin/bash

TMPDIR='/tmp/dci-tmp-dir'
BASEDIR=$(pwd)


get_repo() {
    github=${1}
    repo=$(basename ${github})
    sha=${2}
    roles=${3}
    cd ${TMPDIR}
    git clone https://github.com/${github} ${repo}
    cd ${repo}
    git checkout ${sha}
    cd ${TMPDIR}
    if [ -d ${repo}/roles ]; then
        for i in ${roles}; do
            cp -av ${repo}/roles/${i} ${BASEDIR}/roles/${i}
        done
    else
        cp -av ${repo} ${BASEDIR}/roles/${roles}
        rm -rf ${BASEDIR}/roles/${roles}/.git
    fi
}

rm -Rf ${TMPDIR} ${BASEDIR}/roles
mkdir -p ${TMPDIR} ${BASEDIR}/roles
get_repo openstack/tripleo-quickstart dac8d90aafa7c33dd0c6c9a45926dcc882596597 "common tripleo-inventory"
get_repo openstack/tripleo-quickstart-extras 6eeef321a0aedf610ac8dabb2d3c99f674d28b67 "collect-logs extras-common validate-tempest"
get_repo redhat-cip/ansible-role-openstack-certification 9af8bba9d7e3610a3e4bf2c8bffeae744fe18e3d "certification"

cd ${BASEDIR}/roles
cat << EOF | patch -p1
diff -ru roles2/validate-tempest/tasks/stackviz.yml roles/validate-tempest/tasks/stackviz.yml
--- roles2/validate-tempest/tasks/stackviz.yml	2017-04-11 11:37:46.501719746 -0400
+++ roles/validate-tempest/tasks/stackviz.yml	2017-04-10 15:28:53.352639119 -0400
@@ -9,7 +9,8 @@
   synchronize:
       src: stackviz/
       dest: "{{ working_dir }}/stackviz_static"
-      use_ssh_args: true
+      # TODO(Goneri): https://github.com/ansible/ansible/issues/21774
+      # use_ssh_args: true
 
 - name: Install pip
   easy_install:
diff -ru roles2/validate-tempest/tasks/tempest-results.yml roles/validate-tempest/tasks/tempest-results.yml
--- roles2/validate-tempest/tasks/tempest-results.yml	2017-04-11 11:37:46.501719746 -0400
+++ roles/validate-tempest/tasks/tempest-results.yml	2017-04-10 15:28:53.352639119 -0400
@@ -2,7 +2,7 @@
 - name: Fetch nosetests results
   fetch:
     src: "{{ working_dir }}/tempest/tempest.xml"
-    dest: "{{ lookup('env', 'PWD') }}/nosetests.xml"
+    dest: "{{ local_working_dir }}/nosetests.xml"
     flat: yes
 
 - name: Generate subunit results file
@@ -14,7 +14,7 @@
 - name: Fetch subunit results
   fetch:
     src: "{{ working_dir }}/tempest/results.subunit"
-    dest: "{{ lookup('env', 'PWD') }}/results.subunit"
+    dest: "{{ local_working_dir }}/results.subunit"
     flat: yes
 
 - ignore_errors: true
@@ -36,7 +36,7 @@
     - name: Fetch HTML results
       fetch:
         src: "{{ working_dir }}/tempest/tempest.html"
-        dest: "{{ lookup('env', 'PWD') }}/tempest.html"
+        dest: "{{ local_working_dir}}/tempest.html"
         flat: yes
 
 - name: Exit with tempest result code if configured
--- roles.save/validate-tempest/defaults/main.yml	2017-04-11 13:32:18.846670606 -0400
+++ roles/validate-tempest/defaults/main.yml	2017-04-11 15:29:27.000000000 -0400
@@ -31,6 +31,6 @@
 tempest_exit_on_failure: true
 # Set tempest_version for different release
 # For forked-tempest, we have branched name in synced with releases.
-tempest_version_dict: { 'mitaka': 'mitaka', 'newton': 'newton',
+tempest_version_dict: { 'liberty': 'liberty', 'mitaka': 'mitaka', 'newton': 'newton',
                          'ocata': '15.0.0', 'master': 'master'}
 tempest_version: "{{ tempest_version_dict[release] }}"
Only in roles/validate-tempest/tasks: post-tempest.retry
Only in roles/validate-tempest/tasks: .pre-tempest.yml.swp
Only in roles/validate-tempest/tasks: .tempest-results.yml.swp
diff -ur roles.save/validate-tempest/templates/configure-tempest.sh.j2 roles/validate-tempest/templates/configure-tempest.sh.j2
--- roles.save/validate-tempest/templates/configure-tempest.sh.j2	2017-04-11 13:32:18.847670607 -0400
+++ roles/validate-tempest/templates/configure-tempest.sh.j2	2017-04-11 15:19:09.000000000 -0400
@@ -86,7 +86,7 @@
 {{ working_dir }}/tempest_git/tools/with_venv.sh pip install {{ working_dir }}/tempest_git junitxml
 # Create Tempest Workspace
 cd {{ working_dir }}/tempest
-{% if release in ['mitaka','newton'] %}
+{% if release in ['liberty', 'mitaka','newton'] %}
 {{ working_dir }}/tempest_git/tools/configure-tempest-directory
 {% else %}
 {{ working_dir }}/tempest_git/tools/with_venv.sh tempest init {{ working_dir }}/tempest
@@ -95,7 +95,7 @@
 {% elif tempest_format == "packages" %}
 # Install Tempest Package
 sudo yum -y install openstack-tempest python-junitxml
-{% if release in ['mitaka','newton'] %}
+{% if release in ['liberty', 'mitaka','newton'] %}
 cd {{ working_dir }}/tempest
 /usr/share/openstack-tempest-*/tools/configure-tempest-directory
 {% else %}
@@ -106,7 +106,7 @@
 {% endif %}
 
 # Install OpenStack Services Tempest plugin
-{% if release != "mitaka" %}
+{% if release not in ['liberty', 'mitaka'] %}
 # FIXME(chkumar246): Install tempest plugin from package currently then switch to install_test_packages script
 sudo yum -y install python-ceilometer-tests python-zaqar-tests python-ironic-inspector-tests python-gnocchi-tests \
     python-aodh-tests python-nova-tests python-mistral-tests python-heat-tests python-keystone-tests \
@@ -114,7 +114,7 @@
 {% endif %}
 
 # Generate tempest configuration files
-{% if release in ['mitaka','newton'] %}
+{% if release in ['liberty', 'mitaka','newton'] %}
 export TEMPESTCONF="{{ working_dir }}/tempest/tools/config_tempest.py"
 {% else %}
 {% if tempest_format == "venv" %}
diff -ru roles2/certification/tasks/main.yml roles/certification/tasks/main.yml
--- roles2/certification/tasks/main.yml 2017-04-26 11:02:27.200596104 -0400
+++ roles/certification/tasks/main.yml  2017-04-26 11:03:49.225062744 -0400
@@ -48,5 +48,5 @@
   become: True
   fetch:
     src: cert.txt
-    dest: "{{ lookup('env', 'PWD') }}/cert.txt"
+    dest: "{{ local_working_dir }}/cert.txt"
     flat: yes
diff --git roles2/validate-tempest/defaults/main.yml roles/validate-tempest/defaults/main.yml
--- roles2/validate-tempest/defaults/main.yml
+++ roles/validate-tempest/defaults/main.yml
@@ -31,6 +31,6 @@ tempest_failing: false
 tempest_exit_on_failure: true
 # Set tempest_version for different release
 # For forked-tempest, we have branched name in synced with releases.
-tempest_version_dict: { 'mitaka': 'mitaka', 'newton': 'newton',
-                         'ocata': '16.0.0', 'master': 'master'}
+tempest_version_dict: { 'liberty': 'liberty', 'mitaka': 'mitaka', 'newton': 'newton',
+                         'ocata': '15.0.0', 'master': 'master'}
EOF

curl -q 'https://review.openstack.org/changes/463058/revisions/ee5ffdccd048df13242f48fd5aed8f7e073a2289/patch?download'|base64 -d|patch -p2
