#!/bin/bash
set -eux
TMPDIR='/tmp/dci-tmp-dir'
BASEDIR=$(pwd)

declare -A release
release['OSP8']='liberty'
release['OSP9']='mitaka'
release['OSP10']='newton'
release['OSP11']='ocata'
release['OSP12']='pike'
release['OSP13']='queens'

get_repo() {
    repo=${1}
    roles=${2}
    cd ${TMPDIR}
    git clone https://code.engineering.redhat.com/gerrit/${repo}.git ${repo}
    cd ${repo}
    for topic in "${!release[@]}"; do
        branch=$(echo ${topic}|sed 's,OSP,origin/stable/rhos-,')
        target=${BASEDIR}/roles/${release[$topic]}
        [ "${branch}" = "origin/stable/rhos-13" ] && branch="origin/stable/master"
        [ "${branch}" = "origin/stable/rhos-12" ] && branch="origin/stable/master"
        [ "${branch}" = "origin/stable/rhos-11" ] && branch="origin/stable/master"
        mkdir -p ${target}
        git checkout -b ${topic} ${branch}

        if [ ${repo} = 'tripleo-quickstart-extras' ]; then
            git remote show redhat_gerrit || git remote add redhat_gerrit ssh://code.engineering.redhat.com:22/tripleo-quickstart-extras.git
            [ ${topic} = "OSP13" ] && git review -x 560676
            [ ${topic} = "OSP12" ] && git review -x 560676
            [ ${topic} = "OSP10" ] && git review -r redhat_gerrit -x 135439
            [ ${topic} = "OSP9" ] && git review -r redhat_gerrit -x 130689
            [ ${topic} = "OSP8" ] && git review -r redhat_gerrit -x 130690
            [ ${topic} = "OSP9" ] && git review -r redhat_gerrit -x 130692
            [ ${topic} = "OSP8" ] && git review -r redhat_gerrit -x 130694
	fi

        for i in ${roles}; do
           cp -av roles/${i} ${target}/${i}
        done
	git reset --hard
	git clean -ffdx
    done
}

rm -Rf ${TMPDIR}
mkdir -p ${TMPDIR}

git rm -r roles
get_repo tripleo-quickstart "common tripleo-inventory"
get_repo tripleo-quickstart-extras "collect-logs extras-common validate-tempest"
git add roles
