known_failures:
  - test: 'tempest.api.telemetry.test_telemetry_notification_api'
    reason: 'ospd-8 poodle 2016-02-04.1 tempest.api.telemetry.test_telemetry_notification_api failing'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1304933'
  - test: 'tempest.scenario.test_volume_boot_pattern'
    reason: 'rdo-manager tempest smoke test failing on "floating ip pool not found"'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1272289'
  - test: 'tempest.api.volume.test_volumes_get'
    reason: 'rdo-manager tempest smoke test failing on "floating ip pool not found"'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1272289'
  - test: 'tempest.api.identity.*v3'
    reason: 'Tempest Identify tests failed on V3 api on OSP-D puddle'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1266947'
  - test: 'tempest.api.data_processing'
    reason: 'tempest.api.data_processing tests failing on newton'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1357667'
  - test: 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps'
    reason: 'TestNetworkBasicOps often times out running against tripleo'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1605654'
  - test: 'tempest.api.compute.servers.test_server_actions.ServerActionsTestJSON'
    reason: 'tempest fail: tempest.api.identity.admin.v2.test_services.ServicesTestJSON'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1386421'
  - test: 'tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_cryptsetup'
    reason: 'TripleO does not deploy Barbican by default, which is needed for this test to pass'
  - test: 'tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_luks'
    reason: 'TripleO does not deploy Barbican by default, which is needed for this test to pass'
  - test: 'tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps.test_cross_tenant_traffic'
    reason: 'Security groups firewall rules do not get applied on the compute nodes'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1411690'
  - test: 'tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps.test_multiple_security_groups'
    reason: 'Security groups firewall rules do not get applied on the compute nodes'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1411690'
  - test: 'mistral_tempest_tests.tests'
    reason: 'Skip Mistral tests as it needs to use mistral v2 endpoints'
  - test: 'ceilometer.tests.tempest.api.test_telemetry_notification_api.TelemetryNotificationAPITest'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'ceilometer.tests.tempest.api.test_telemetry_notification_api.TelemetryNotificationAdminAPITest'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'ceilometer.tests.tempest.scenario.test_object_storage_telemetry_middleware.TestObjectStorageTelemetry'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'neutron.tests.tempest.scenario.test_dvr.NetworkDvrTest'
    reason: 'TODO(arxcruz) New test, need investigation'
  - test: 'neutron.tests.tempest.scenario.test_trunk.TrunkTest'
    reason: 'TODO(arxcruz) New test, need investigation'
