- name: Retrieve component
  dci_component:
    dest: '{{ dci_cache_dir }}/{{ item["id"] }}.tar'
    id: '{{ item["id"] }}'
  with_items: "{{ components }}"

- name: Unarchive component
  unarchive:
    src: '{{ dci_cache_dir }}/{{ item["id"] }}.tar'
    dest: '{{ dci_mirror_location }}/dci_repo'
    remote_src: True
    list_files: yes
  with_items: "{{ components }}"

- name: Prepare the YUM repo file
  yum_repository:
    name: '{{ item["canonical_project_name"] }}'
    description: '{{ item["canonical_project_name"] }}'
    baseurl: '{{ dci_baseurl }}/dci_repo/{{ item["canonical_project_name"] }}/'
    gpgcheck: no
    file: '{{ dci_mirror_location }}/dci_repo/dci_repo'
  with_items: '{{ job_informations["job"]["components"] }}'

- include: sync_registry.yaml
  when: dci_topic in ['OSP12', 'OSP13']

